apiVersion: kubeflow.org/v1
kind: Workspace
metadata:
  name: my-notebook
  namespace: my-namespace
spec:
  ## if the workspace should be paused (no pods running)
  paused: false

  ## the WorkspaceKind to use
  kind: "juptyer-lab"

  ## options for WorkspaceKinds that are "podTemplate"-type
  ##
  podTemplate:

    ## option configs (defined by the WorkspaceKind)
    ##
    options:
      image: "jupyter_scipy_170"
      podConfig: "big_gpu"

    ## volume configs
    ##
    volumes:
      homePVC: "my-home-pvc"
      dataPVCs:
        - name: "my-data-pvc"
          mountPath: /data/my-data

    ## metadata to be applied to the Pod resource
    ##
    podMetadata:

      ## labels are required to support the existing PodDefault resources
      ##  - our controller needs to NOT revert changes made by admission webhooks.
      ##    we can achieve this using a StatefulSet instead of making the Pod directly,
      ##    this is what we do for the existing Notebook controller.
      ##  - here are the fields of a PodDefault resource:
      ##    https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
      ##
      labels: {}

      ## annotations are commonly used to configure other controllers that watch the Pod
      ##
      annotations: {}

## ================================================================
## status (managed by controller)
## ================================================================
status:
  ## information populated by activity probes, used to determine when to cull
  activity:
    lastActivity: 1710435303 # UNIX epoch
    lastUpdate: 1710435310 # UNIX epoch

  ## if the current Pod does not reflect the current "desired" state (after redirects)
  pendingRestart: false

  ## actual "target" podTemplateOptions, taking into account redirects
  podTemplateOptions:
    image: "jupyter_scipy_171"
    podConfig: "big_gpu"