apiVersion: kubeflow.org/v1beta1
kind: Workspace
metadata:
  name: my-notebook
  namespace: my-namespace
spec:
  ## if the workspace is paused (no pods running)
  paused: false

  ## the WorkspaceKind to use
  kind: "juptyer-lab"

  ## options for "podTemplate"-type WorkspaceKinds
  ##
  podTemplate:

    ## metadata to be applied to the Pod resource
    ##
    podMetadata:

      ## labels to be applied to the Pod resource
      ##  - labels are required to support integration with the PodDefault resource:
      ##    https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go
      ##
      labels: {}

      ## annotations to be applied to the Pod resource
      ##
      annotations: {}

    ## volume configs
    ##
    volumes:

      ## the name of the PVC to mount as the home volume
      ##  - this PVC must already exist in the Namespace
      ##  - this PVC must be RWX (ReadWriteMany, ReadWriteOnce)
      ##  - the mount path is defined in the WorkspaceKind under
      ##    `spec.podTemplate.volumeMounts.home`
      ##
      home: "my-home-pvc"

      ## additional PVCs to mount
      ##  - these PVC must already exist in the Namespace
      ##  - these PVC must be RWX (ReadWriteMany, ReadWriteOnce)
      ##
      data:
        - name: "my-data-pvc"
          mountPath: /data/my-data

    ## the selected podTemplate options
    ##  - these are the user-selected options from the Workspace Spawner UI
    ##    which determine the PodSpec of the Workspace Pod
    ##
    options:

      ## the id of an imageConfig option
      ##  - options are defined in WorkspaceKind under
      ##    `spec.podTemplate.options.imageConfig.values[]`
      ##
      imageConfig: "jupyter_scipy_170"

      ## the id of a podConfig option
      ##  - options are defined in WorkspaceKind under
      ##    `spec.podTemplate.options.podConfig.values[]`
      ##
      podConfig: "big_gpu"

## ================================================================
## status (managed by controller)
## ================================================================
status:
  ## activity information for the Workspace, used to determine when to cull
  activity:

    ## the last time activity was observed on the Workspace (UNIX epoch)
    lastActivity: 1710435303

    ## the last time we checked for activity on the Workspace (UNIX epoch)
    lastUpdate: 1710435310 # UNIX epoch

  ## the time when the Workspace was paused, 0 if the Workspace is not paused
  pauseTime: 0 # UNIX epoch

  ## if the current Pod does not reflect the current "desired" state
  ##  - true if any `spec.podTemplate.options` have a redirect
  ##    and so will be patched on the next restart
  ##  - true if the WorkspaceKind has changed one of its common `podTemplate` fields
  ##    like `podMetadata`, `probes`, `extraEnv`, or `containerSecurityContext`
  pendingRestart: true

  ## the `spec.podTemplate.options` which will take effect after the next restart
  podTemplateOptions:
    imageConfig: "jupyter_scipy_171"
    podConfig: "big_gpu"

  ## the current state of the Workspace
  ##  - ENUM: "Running" | "Terminating" | "Paused" | "Pending" | "Error" | "Unknown"
  state: "Running"

  ## a human-readable message about the state of the Workspace
  ##  - WARNING: this field is NOT FOR MACHINE USE, subject to change without notice
  stateMessage: ""