apiVersion: kubeflow.org/v1
kind: Workspace
metadata:
  name: my-notebook
  namespace: my-namespace
spec:
  ## if the workspace should be paused (no pods running)
  paused: false

  ## the WorkspaceKind to use
  kind: "juptyer-lab"

  ## options for WorkspaceKinds that are "podTemplate"-type
  ##
  podTemplate:

    ## option configs (defined by the WorkspaceKind)
    ##
    options:
      image: "jupyter_scipy_170"
      podConfig: "big_gpu"

    ## volume configs
    ##
    volumes:
      homePVC: "my-home-pvc"
      dataPVCs:
        - name: "my-data-pvc"
          mountPath: /data/my-data

    ## metadata to be applied to the Pod resource
    ##
    podMetadata:
      labels: {}
      annotations: {}

## ================================================================
## status (managed by controller)
## ================================================================
status:
  ## information populated by activity probes, used to determine when to cull
  activity:
    lastActivity: 1710435303 # UNIX epoch
    lastUpdate: 1710435310 # UNIX epoch

  ## if the current Pod does not reflect the current "desired" state (after redirects)
  pendingRestart: false

  ## actual "target" podTemplateOptions, taking into account redirects
  podTemplateOptions:
    image: "jupyter_scipy_171"
    podConfig: "big_gpu"